{% set name = "unasync" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9d01ace3e1068b20550ab15b7f9723b15b8bcde728bc1770bcb578374c7ee58

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - setuptools >=40.6.2
    - tokenize-rt

test:
  imports:
    - unasync

about:
  home: https://github.com/python-trio/unasync
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: The async transformation code
  doc_url: https://unasync.readthedocs.io
  dev_url: https://github.com/python-trio/unasync

extra:
  recipe-maintainers:
    - davidbrochart
    - sethmlarson
